version: '3.8'
services:
  analytics-panel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - STRATEGY_SERVICE_URL=${STRATEGY_SERVICE_URL}
      - DB_URL=${DB_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_TYPE=${DB_TYPE}
    volumes:
      - .:/app

  strategy-service:
    build:
      context: ./strategy-service
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - DB_TYPE=${DB_TYPE}

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
