version: '3.8'
services:
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
  order_service:
    image: your_order_service_image
    ports:
      - '4000:4000'
  user_service:
    image: your_user_service_image
    ports:
      - '5000:5000'
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitoring_db
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: