version: '3.8'
services:
  price-aggregator:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - BASE_URL=${BASE_URL}
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - DOCKER=${DOCKER}
    volumes:
      - .:/usr/src/app
    networks:
      - price-aggregator-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    networks:
      - price-aggregator-network

networks:
  price-aggregator-network:
    driver: bridge