version: '3.8'
services:
  price-aggregator:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - BASE_URL=https://api.example.com
      - PORT=3000
    volumes:
      - .:/usr/src/app
    networks:
      - price-aggregator-network

networks:
  price-aggregator-network:
    driver: bridge
