version: '3.8'
services:
  auth-layer:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    ports:
      - '4000:4000'

  order-service:
    build:
      context: ../order-service
      dockerfile: Dockerfile
    ports:
      - '5000:5000'