version: '3.8'
services:
  admin-console:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: admin_console
    ports:
      - '5432:5432'
    restart: always